zuul:
  host:
    max-total-connections: 1000
    max-per-route-connections: 100
  semaphore:
    max-semaphores: 500
  ignoredServices: 'consul,gateway'

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

management:
  security:
    roles: ADMIN
  context-path: /management
spring:
  application:
    name: gateway
  cloud:
    consul:
      discovery:
        healthCheckPath: /management/health
        instanceId: ${spring.application.name}:${spring.application.instance-id:${random.value}}
  jackson:
    serialization.write_dates_as_timestamps: false
  mvc:
    favicon:
      enabled: false
security:
  basic:
    enabled: false
  oauth2:
    resource:
      filter-order: 3

server:
  session:
    cookie:
      http-only: true

info:
  project:
    version: #project.version#


mimiron:
  #cors:
    #allowed-origins: "*"
    #allowed-methods: GET, PUT, POST, DELETE, OPTIONS
    #allowed-headers: "*"
    #exposed-headers:
    #allow-credentials: true
    #max-age: 1800
  swagger:
    default-include-pattern: /api/.*
    title: gateway API
    description: gateway API documentation
    version: 0.0.1
    terms-of-service-url:
    contact-name:
    contact-url:
    contact-email:
    license:
    license-url:
  ribbon:
    display-on-active-profiles: dev
